-- Esquema base del proyecto (exportado de producción el 26/09/2026).
--
-- Las tablas originales se crearon a mano en el dashboard de Supabase, así
-- que el historial de migraciones remoto (jul 2026) no alcanza para
-- reconstruir la base desde cero. Este archivo consolida TODO ese historial:
-- es el punto de partida para levantar una base nueva.
--
-- Ya incluye los arreglos de seguridad de la migración siguiente
-- (20260926202646_seguridad_registro_y_roles), que vuelve a definir las
-- mismas funciones; aplicarla después no cambia nada.
--
-- Las tablas usan los permisos por defecto de Supabase para anon/authenticated;
-- lo que cada rol puede ver o tocar lo deciden las políticas RLS de abajo.

-- ===== TABLAS =====

create table public.clientes (
  id bigint generated by default as identity,
  nombre text not null,
  telefono text not null,
  correo text,
  direccion text,
  fecha_ingreso timestamp with time zone not null default now(),
  es_demo boolean not null default false,
  user_id uuid,
  bloqueado boolean not null default false
);

create table public.ordenes (
  id bigint generated by default as identity,
  id_vehiculo bigint not null,
  fecha_ingreso timestamp with time zone not null default now(),
  descripcion text,
  diagnostico text,
  estado text not null,
  costo_estimado text,
  costo_final text not null,
  fecha_entrega timestamp without time zone not null,
  es_demo boolean not null default false
);

create table public.solicitudes_vinculacion (
  id bigint generated always as identity,
  user_id uuid not null,
  telefono_ingresado text,
  cliente_id bigint,
  estado text not null default 'pendiente'::text,
  comentario_admin text,
  fecha_solicitud timestamp with time zone not null default now(),
  fecha_resolucion timestamp with time zone
);

create table public.usuarios (
  id uuid not null,
  nombre text not null,
  correo text not null,
  rol text not null default 'cliente'::text,
  fecha_registro timestamp with time zone not null default now()
);

create table public.vehiculos (
  id bigint generated by default as identity,
  id_cliente bigint,
  placa text not null,
  marca text,
  modelo text,
  "año" integer,
  color text,
  kilometraje text,
  es_demo boolean not null default false,
  ultima_revision_tecnica date
);

-- ===== RESTRICCIONES =====

alter table public.clientes add constraint clientes_pkey PRIMARY KEY (id);
alter table public.ordenes add constraint ordenes_pkey PRIMARY KEY (id);
alter table public.solicitudes_vinculacion add constraint solicitudes_vinculacion_pkey PRIMARY KEY (id);
alter table public.usuarios add constraint usuarios_pkey PRIMARY KEY (id);
alter table public.vehiculos add constraint vehiculo_pkey PRIMARY KEY (id);
alter table public.usuarios add constraint usuarios_correo_key UNIQUE (correo);
alter table public.solicitudes_vinculacion add constraint solicitudes_vinculacion_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'aprobada'::text, 'rechazada'::text])));
alter table public.usuarios add constraint usuarios_rol_check CHECK ((rol = ANY (ARRAY['admin'::text, 'demo'::text, 'cliente'::text])));
alter table public.clientes add constraint clientes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.ordenes add constraint ordenes_id_vehiculo_fkey FOREIGN KEY (id_vehiculo) REFERENCES vehiculos(id);
alter table public.solicitudes_vinculacion add constraint solicitudes_vinculacion_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
alter table public.solicitudes_vinculacion add constraint solicitudes_vinculacion_user_id_fkey FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE CASCADE;
alter table public.usuarios add constraint usuarios_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.vehiculos add constraint vehiculos_id_cliente_fkey FOREIGN KEY (id_cliente) REFERENCES clientes(id);

-- ===== ÍNDICES =====

CREATE INDEX idx_solicitudes_vinculacion_user_id ON public.solicitudes_vinculacion USING btree (user_id);
CREATE UNIQUE INDEX clientes_user_id_key ON public.clientes USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX idx_solicitudes_vinculacion_estado ON public.solicitudes_vinculacion USING btree (estado);

-- ===== FUNCIONES =====

CREATE OR REPLACE FUNCTION public.bloquear_desvinculacion_cliente()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if old.user_id is not null and new.user_id is null then
    raise exception 'Una cuenta ya vinculada no se puede desvincular.';
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.eliminar_cliente_completo(p_cliente_id bigint, p_modo text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_rol text := coalesce(public.get_my_role(), '');
  v_es_demo boolean;
  v_user_id uuid;
  v_ordenes_activas int;
begin
  select es_demo, user_id into v_es_demo, v_user_id
  from public.clientes
  where id = p_cliente_id;

  if not found then
    raise exception 'El cliente no existe.';
  end if;

  if (v_es_demo and v_rol <> 'demo') or (not v_es_demo and v_rol <> 'admin') then
    raise exception 'No tienes permiso para eliminar este cliente.';
  end if;

  if p_modo not in ('todo', 'conservar_historial') then
    raise exception 'Modo de eliminación inválido.';
  end if;

  select count(*) into v_ordenes_activas
  from public.ordenes o
  join public.vehiculos v on v.id = o.id_vehiculo
  where v.id_cliente = p_cliente_id
    and o.estado in ('Pendiente', 'En proceso');

  if v_ordenes_activas > 0 then
    raise exception 'Este cliente tiene % orden(es) pendiente(s) o en proceso. Complétalas o cancélalas antes de eliminar.', v_ordenes_activas;
  end if;

  if p_modo = 'todo' then
    delete from public.ordenes where id_vehiculo in (select id from public.vehiculos where id_cliente = p_cliente_id);
    delete from public.vehiculos where id_cliente = p_cliente_id;
  else
    update public.vehiculos set id_cliente = null where id_cliente = p_cliente_id;
  end if;

  delete from public.clientes where id = p_cliente_id;

  if v_user_id is not null then
    delete from auth.users where id = v_user_id;
  end if;
end;
$function$;

CREATE OR REPLACE FUNCTION public.enforce_es_demo_flag()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if TG_OP = 'INSERT' then
    if public.get_my_role() = 'demo' then
      new.es_demo := true;
    else
      new.es_demo := false;
    end if;
  elsif TG_OP = 'UPDATE' then
    -- el flag es inmutable una vez creada la fila
    new.es_demo := old.es_demo;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fusionar_cliente_vinculado(p_cliente_destino_id bigint, p_usuario_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_cliente_origen_id bigint;
  v_direccion_origen text;
begin
  if coalesce(public.get_my_role(), '') <> 'admin' then
    raise exception 'Solo un administrador puede vincular o fusionar cuentas.';
  end if;

  select id into v_cliente_origen_id
  from public.clientes
  where user_id = p_usuario_id;

  if v_cliente_origen_id is null then
    update public.clientes set user_id = p_usuario_id where id = p_cliente_destino_id;
    return;
  end if;

  if v_cliente_origen_id = p_cliente_destino_id then
    raise exception 'Esa cuenta ya está vinculada a esta misma ficha.';
  end if;

  select direccion into v_direccion_origen from public.clientes where id = v_cliente_origen_id;

  -- Los datos que el cliente puso (fichaorigen, la de su cuenta autoregistrada)
  -- siempre tienen prioridad sobre lo que haya puesto el admin en el destino,
  -- igual que ya pasa con nombre/correo/telefono via el trigger de sincronización.
  if v_direccion_origen is not null and v_direccion_origen <> '' then
    update public.clientes set direccion = v_direccion_origen where id = p_cliente_destino_id;
  end if;

  update public.vehiculos set id_cliente = p_cliente_destino_id where id_cliente = v_cliente_origen_id;

  delete from public.clientes where id = v_cliente_origen_id;

  update public.clientes set user_id = p_usuario_id where id = p_cliente_destino_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.get_my_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select rol from public.usuarios where id = auth.uid();
$function$;

CREATE OR REPLACE FUNCTION public.get_stats_publicas()
 RETURNS json
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select json_build_object(
    'clientes', (select count(*) from public.clientes where es_demo = false),
    'vehiculos', (select count(*) from public.vehiculos where es_demo = false),
    'ordenes_completadas', (
      select count(*) from public.ordenes
      where es_demo = false and estado = 'Completado'
    )
  );
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_telefono text;
  v_cliente_id bigint;
  v_nombre text;
  v_correo_verificado boolean;
begin
  v_nombre := coalesce(
    new.raw_user_meta_data->>'nombre',
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'name',
    ''
  );

  -- A1: nunca se toma el rol de la metadata del registro.
  insert into public.usuarios (id, nombre, correo, rol)
  values (new.id, v_nombre, new.email, 'cliente');

  v_telefono := coalesce(new.raw_user_meta_data->>'telefono', '');

  -- A2: solo se confía en el correo cuando lo verificó un proveedor OAuth.
  v_correo_verificado :=
    new.email_confirmed_at is not null
    and coalesce(new.raw_app_meta_data->>'provider', 'email') <> 'email';

  if v_correo_verificado then
    select id into v_cliente_id
    from public.clientes
    where user_id is null
      and es_demo = false
      and correo is not null
      and lower(correo) = lower(new.email)
    order by fecha_ingreso desc
    limit 1;
  end if;

  if v_cliente_id is not null then
    -- ya existía una ficha (creada por el admin) con ese mismo correo
    -- verificado: se vincula directamente.
    update public.clientes set user_id = new.id where id = v_cliente_id;
  else
    -- se crea una ficha nueva para que la persona aparezca en Clientes;
    -- si el taller ya tenía una ficha suya, el admin las fusiona.
    insert into public.clientes (nombre, correo, telefono, user_id, es_demo)
    values (v_nombre, new.email, v_telefono, new.id, false);
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.proteger_bloqueo_cliente()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.bloqueado is distinct from old.bloqueado
     and coalesce(public.get_my_role(), '') not in ('admin', 'demo') then
    raise exception 'No tienes permiso para cambiar el estado de bloqueo de este cliente.';
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.proteger_datos_cliente_vinculado()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- Si quien actualiza es admin y la fila ya estaba vinculada y sigue vinculada
  -- a la misma persona, no se permite tocar los datos de contacto: esos los
  -- controla únicamente el cliente desde su propio portal.
  if get_my_role() = 'admin'
     and old.user_id is not null
     and new.user_id is not distinct from old.user_id then
    if new.nombre is distinct from old.nombre
       or new.telefono is distinct from old.telefono
       or new.correo is distinct from old.correo
       or new.direccion is distinct from old.direccion then
      raise exception 'Este cliente ya está vinculado a una cuenta. Sus datos de contacto ahora los administra directamente desde su portal.';
    end if;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.proteger_rol_usuario()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.rol is distinct from old.rol
     -- viene de la API (con JWT), no de una conexión directa a la base
     and nullif(current_setting('request.jwt.claims', true), '') is not null
     and coalesce(auth.jwt()->>'role', '') <> 'service_role'
     and coalesce(public.get_my_role(), '') <> 'admin' then
    raise exception 'No tienes permiso para cambiar el rol de este usuario.';
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.sincronizar_correo_usuario()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.email is distinct from old.email then
    update public.usuarios set correo = new.email where id = new.id;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.sincronizar_datos_cliente_vinculado()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_nombre text;
  v_correo text;
  v_telefono text;
begin
  -- Se sincroniza únicamente cuando se está estableciendo o cambiando el
  -- vínculo a una cuenta (no en cada edición posterior). Los datos del
  -- cliente vinculado tienen prioridad sobre lo que haya puesto el admin.
  if new.user_id is not null
     and (old.user_id is null or old.user_id is distinct from new.user_id) then

    select u.nombre, u.correo, au.raw_user_meta_data->>'telefono'
      into v_nombre, v_correo, v_telefono
    from public.usuarios u
    join auth.users au on au.id = u.id
    where u.id = new.user_id;

    if v_nombre is not null and v_nombre <> '' then
      new.nombre := v_nombre;
    end if;

    if v_correo is not null and v_correo <> '' then
      new.correo := v_correo;
    end if;

    if v_telefono is not null and v_telefono <> '' then
      new.telefono := v_telefono;
    end if;
  end if;

  return new;
end;
$function$;

-- ===== PERMISOS DE FUNCIONES =====
-- Primero se quita todo y luego se da solo lo necesario.

revoke all on function public.bloquear_desvinculacion_cliente() from public, anon, authenticated;
revoke all on function public.eliminar_cliente_completo(p_cliente_id bigint, p_modo text) from public, anon, authenticated;
revoke all on function public.enforce_es_demo_flag() from public, anon, authenticated;
revoke all on function public.fusionar_cliente_vinculado(p_cliente_destino_id bigint, p_usuario_id uuid) from public, anon, authenticated;
revoke all on function public.get_my_role() from public, anon, authenticated;
revoke all on function public.get_stats_publicas() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.proteger_bloqueo_cliente() from public, anon, authenticated;
revoke all on function public.proteger_datos_cliente_vinculado() from public, anon, authenticated;
revoke all on function public.proteger_rol_usuario() from public, anon, authenticated;
revoke all on function public.sincronizar_correo_usuario() from public, anon, authenticated;
revoke all on function public.sincronizar_datos_cliente_vinculado() from public, anon, authenticated;

grant execute on function public.bloquear_desvinculacion_cliente() to service_role;
grant execute on function public.eliminar_cliente_completo(p_cliente_id bigint, p_modo text) to authenticated;
grant execute on function public.eliminar_cliente_completo(p_cliente_id bigint, p_modo text) to service_role;
grant execute on function public.enforce_es_demo_flag() to anon;
grant execute on function public.enforce_es_demo_flag() to authenticated;
grant execute on function public.enforce_es_demo_flag() to service_role;
grant execute on function public.fusionar_cliente_vinculado(p_cliente_destino_id bigint, p_usuario_id uuid) to authenticated;
grant execute on function public.fusionar_cliente_vinculado(p_cliente_destino_id bigint, p_usuario_id uuid) to service_role;
grant execute on function public.get_my_role() to authenticated;
grant execute on function public.get_my_role() to service_role;
grant execute on function public.get_stats_publicas() to anon;
grant execute on function public.get_stats_publicas() to authenticated;
grant execute on function public.get_stats_publicas() to service_role;
grant execute on function public.handle_new_user() to service_role;
grant execute on function public.proteger_bloqueo_cliente() to service_role;
grant execute on function public.proteger_datos_cliente_vinculado() to service_role;
grant execute on function public.proteger_rol_usuario() to service_role;
grant execute on function public.sincronizar_correo_usuario() to service_role;
grant execute on function public.sincronizar_datos_cliente_vinculado() to service_role;

-- ===== TRIGGERS =====

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER trg_sincronizar_correo_usuario AFTER UPDATE ON auth.users FOR EACH ROW EXECUTE FUNCTION sincronizar_correo_usuario();
CREATE TRIGGER trg_bloquear_desvinculacion_cliente BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION bloquear_desvinculacion_cliente();
CREATE TRIGGER trg_clientes_es_demo BEFORE INSERT OR UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION enforce_es_demo_flag();
CREATE TRIGGER trg_proteger_bloqueo_cliente BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION proteger_bloqueo_cliente();
CREATE TRIGGER trg_proteger_datos_cliente_vinculado BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION proteger_datos_cliente_vinculado();
CREATE TRIGGER trg_sincronizar_datos_cliente_vinculado BEFORE INSERT OR UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION sincronizar_datos_cliente_vinculado();
CREATE TRIGGER trg_ordenes_es_demo BEFORE INSERT OR UPDATE ON public.ordenes FOR EACH ROW EXECUTE FUNCTION enforce_es_demo_flag();
CREATE TRIGGER trg_proteger_rol_usuario BEFORE UPDATE ON public.usuarios FOR EACH ROW EXECUTE FUNCTION proteger_rol_usuario();
CREATE TRIGGER trg_vehiculos_es_demo BEFORE INSERT OR UPDATE ON public.vehiculos FOR EACH ROW EXECUTE FUNCTION enforce_es_demo_flag();

-- ===== SEGURIDAD (RLS) =====

alter table public.clientes enable row level security;
alter table public.ordenes enable row level security;
alter table public.solicitudes_vinculacion enable row level security;
alter table public.usuarios enable row level security;
alter table public.vehiculos enable row level security;

create policy clientes_delete_scoped on public.clientes as permissive for delete to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))));

create policy clientes_insert_scoped on public.clientes as permissive for insert to public
  with check ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))));

create policy clientes_select_scoped on public.clientes as permissive for select to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true)) OR ((get_my_role() = 'cliente'::text) AND (es_demo = false) AND (user_id = auth.uid()))));

create policy clientes_update_scoped on public.clientes as permissive for update to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))))
  with check ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))));

create policy clientes_update_self on public.clientes as permissive for update to public
  using (((get_my_role() = 'cliente'::text) AND (es_demo = false) AND (user_id = auth.uid())))
  with check (((get_my_role() = 'cliente'::text) AND (es_demo = false) AND (user_id = auth.uid())));

create policy ordenes_delete_scoped on public.ordenes as permissive for delete to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))));

create policy ordenes_insert_scoped on public.ordenes as permissive for insert to public
  with check ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))));

create policy ordenes_select_scoped on public.ordenes as permissive for select to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true)) OR ((get_my_role() = 'cliente'::text) AND (es_demo = false) AND (id_vehiculo IN ( SELECT v.id
   FROM (vehiculos v
     JOIN clientes c ON ((c.id = v.id_cliente)))
  WHERE (c.user_id = auth.uid()))))));

create policy ordenes_update_scoped on public.ordenes as permissive for update to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))))
  with check ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))));

create policy solicitudes_insert_scoped on public.solicitudes_vinculacion as permissive for insert to public
  with check (((get_my_role() = 'cliente'::text) AND (user_id = auth.uid()) AND (estado = 'pendiente'::text)));

create policy solicitudes_select_scoped on public.solicitudes_vinculacion as permissive for select to public
  using (((get_my_role() = 'admin'::text) OR ((get_my_role() = 'cliente'::text) AND (user_id = auth.uid()))));

create policy solicitudes_update_admin on public.solicitudes_vinculacion as permissive for update to public
  using ((get_my_role() = 'admin'::text))
  with check ((get_my_role() = 'admin'::text));

create policy usuarios_select_own_or_admin on public.usuarios as permissive for select to public
  using (((auth.uid() = id) OR (get_my_role() = 'admin'::text)));

create policy usuarios_update_admin on public.usuarios as permissive for update to public
  using ((get_my_role() = 'admin'::text))
  with check ((get_my_role() = 'admin'::text));

create policy usuarios_update_own on public.usuarios as permissive for update to public
  using ((auth.uid() = id));

create policy vehiculos_delete_scoped on public.vehiculos as permissive for delete to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))));

create policy vehiculos_insert_scoped on public.vehiculos as permissive for insert to authenticated
  with check ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true)) OR ((get_my_role() = 'cliente'::text) AND (es_demo = false) AND (id_cliente IN ( SELECT c.id
   FROM clientes c
  WHERE (c.user_id = auth.uid()))))));

create policy vehiculos_select_scoped on public.vehiculos as permissive for select to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true)) OR ((get_my_role() = 'cliente'::text) AND (es_demo = false) AND (id_cliente IN ( SELECT clientes.id
   FROM clientes
  WHERE (clientes.user_id = auth.uid()))))));

create policy vehiculos_update_scoped on public.vehiculos as permissive for update to public
  using ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))))
  with check ((((get_my_role() = 'admin'::text) AND (es_demo = false)) OR ((get_my_role() = 'demo'::text) AND (es_demo = true))));
